BEGIN;

--SET session_replication_role = 'replica';
--SET session_replication_role = 'origin';
--disable foreign keys check before dropping tables to prevent dependency conflicts


DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS following;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;


CREATE TABLE users(
  username VARCHAR(20) PRIMARY KEY, --username, at most 20 chars, primary key
  fullname VARCHAR(40), --fullname, at most 40 chars
  email VARCHAR(40), --email, at most 40 chars
  filename VARCHAR(64), --filename, at most 64 chars
  password VARCHAR(256), --password, at most 256 chars,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP --created, TIMESTAMP type, automatically set by SQL engine to current date/time.
);

CREATE TABLE posts (
  postid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --postid, integer, primary key, automatically incremented with AUTOINCREMENT
  filename VARCHAR(64) NOT NULL, --filename, at most 64 chars
  owner VARCHAR(20),
  FOREIGN KEY (owner) REFERENCES users(username) ON DELETE CASCADE, --owner, at most 20 chars, foreign key to users.
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP --created, TIMESTAMP type, automatically set by SQL engine to current date/time.
); --dont forget to end all SQL statements with a ; lol

-- Create following table
CREATE TABLE following (
  follower VARCHAR(20), --follower, at most 20 chars, foreign key to users.
  followee VARCHAR(20), --followee, at most 20 chars, foreign key to users.
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --The tuple (follower, followee) form a primary key
  PRIMARY KEY (follower, followee), --created, TIMESTAMP type, automatically set by SQL engine to current date/time.
  FOREIGN KEY (follower) REFERENCES users(username) ON DELETE CASCADE, --Rows in the following table should be removed automatically when a user corresponding to follower or followee is deleted.
  FOREIGN KEY (followee) REFERENCES users(username) ON DELETE CASCADE --The following relation is follower follows followee.
);

CREATE TABLE comments (
  commentid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner VARCHAR(20) REFERENCES users(username) ON DELETE CASCADE,
  postid INT REFERENCES posts(postid) ON DELETE CASCADE,
  text VARCHAR(1024),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE likes (
  likeid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner VARCHAR(20) REFERENCES users(username) ON DELETE CASCADE,
  postid INT REFERENCES posts(postid) ON DELETE CASCADE,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SET CONSTRAINTS ALL DEFERRED;

COMMIT;
